apiVersion: v1
kind: Pod
metadata: {}
spec:
  serviceAccount: jenkins-operator-jenkins
  containers:
    - name: Kaniko
      image: gcr.io/Kaniko-project/executor:debug
      imagePullPolicy: Always
      command:
        - /busybox/cat
      tty: true
    - name: ubuntu
      image: ubuntu:22.04
      tty: true
      env:
        - name: GIT_SSL_NO_VERIFY
          value: "true"